project:
  type: book
  output-dir: docs

language:
  locale: pt
  title-block-author-single: "Professor"
#  title-block-published: "Publicado em"
#  title-block-modified: "Atualizado em"
#  title-block-author-multiple: "Autores"
#  fig: "Figura"
#  tab: "Tabela"
#  eq: "Equa√ß√£o"
  callout-tip-title: "Dica"
  callout-note-title: "Nota"
  toc-title: "Conte√∫do da aula"

book:
  title: "An√°lise e Express√£o Textual"
  author: "M√°rio Martins"

  chapters:
    - part: "Apresenta√ß√£o"
      chapters:
      - index.qmd
      - Aula_00.qmd

    - part: "Unidade I"
      chapters:
       - Aula_1.qmd
       - Aula_2.qmd
       - Aula_3.qmd
#      - Aula_4.qmd
#      - Aula_5.qmd
#      - Aula_6.qmd
#      - Aula_7.qmd
#      - Aula_8.qmd

#    - part: "Unidade II"
#      chapters:
#      - Aula_9.qmd
#      - Aula_10.qmd
#      - Aula_11.qmd
#      - Aula_12.qmd
#      - Aula_13.qmd
#      - Aula_14.qmd

#    - part: "Unidade III"
#      chapters:
#      - Aula_15.qmd
#      - Aula_16.qmd
#      - part: "Tutoriais"

    - part: "Tutoriais"
      chapters:
       - tutorial_lattes.qmd
#      - tutorial_zotero.qmd
#      - tutorial_capes.qmd
#      - tutorial_tema_pesquisa.qmd
#      - checklist_postagem.qmd

#    - part: "Modelos"
#      chapters:
#      - modelo_plano.qmd
#      - modelo_relatorio.qmd
#      - modelo_video.qmd
#      - modelo_carrossel.qmd

#    - part: "Avalia√ß√µes"
#      chapters:
#      - 1_Avaliacao.qmd
#      - 2_Avaliacao.qmd
#      - 3_Avaliacao.qmd

    - part: "Complementos"
      chapters:
#      - Aula_crono.qmd
#      - sorteio.qmd
       - padlet.qmd
       - portifolio.qmd

# bibliography: references.bib

format:
  html:
    page-layout: full
    highlight-style: github
    theme: 
      - simplex # Experimente tamb√©m: flatly, litera, simplex, journal
    toc: true
    include-after-body: custom.html
    callout-appearance: simple
    smooth-scroll: true
    sidebar:
      style: "docked"
      collapse-level: 1
      pinned: true
    tools:
      - toggle
    css: custom.css

editor: visual


# Como Visualizar o Livro Localmente Antes de Publicar
# üü¢ 1. Renderize o Livro Localmente
# No terminal do RStudio:
# quarto render (no terminal)
# üü¢ 2. Pr√©-visualize o Livro Localmente
# quarto preview docs (no terminal)

# üìã Roteiro Resumido de Atualiza√ß√µes Finais
# Sempre que desejar atualizar o conte√∫do do livro:
#	1.	Edite seu .qmd normalmente no RStudio.
#	2.	Renderize novamente:
# quarto render (no terminal)
# Envie ao GitHub:
# git add .
# git commit -m "Atualiza conte√∫do das aulas"
# git push origin main


